- name: Prompt variables
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
    
  - name: password
    promt: what is your password?
    private: true

  tasks:
  - name: printing username and password
    ansible.builtin.debug:
      msg: "username is {{ username }} and password is {{ password}}"