- name: functions
  hosts: local
  connection: local
  tasks: 
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Bhaskar')}}"

  - name: using shell command
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output

  - name: printing command output
    ansible.builtin.debug:
      msg: "{{ command_output}}"

  - name: redirect the output
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    registed: redirect_op
    ignore_errors: true

  - name: printing redirect output
    ansible.builtin.debug:
      msg: {{ redirect_op}}

