- name: Error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: checking roboshop exit or not
    ansible.builtin.command: id roboshop
    register: robo_output

  - name: printing roboshop output
    ansible.builtin.debug:
      msg: "{{robo_output}}"

  - name: create user
    ansible.builtin.command: useradd roboshop
    when: robo_output.rc !=0